apiVersion: weka.weka.io/v1alpha1
kind: WekaContainer
metadata:
  name: weka-drivers-dist
  namespace: weka-operator-system
  labels:
    app: weka-drivers-dist
spec:
  name: dist
  mode: drivers-dist
  image: quay.io/weka.io/weka-in-container:4.4.10.150
  imagePullSecret: "quay-io-robot-secret"
  agentPort: 60001
  exposedPorts:
    containerPorts:
      - port: 60002
        protocol: TCP
  cpuPolicy: auto
  numCores: 1
  state: active
  upgradePolicyType: manual
  network:
    udpMode: true
---
apiVersion: v1
kind: Service
metadata:
  name: weka-drivers-dist
  namespace: weka-operator-system
spec:
  type: ClusterIP
  ports:
    - name: weka-drivers-dist
      port: 60002
      targetPort: 60002
  selector:
    app: weka-drivers-dist
