{{- if .Values.customResourceDefinition.create }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wekaappstores.warp.io
spec:
  group: warp.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # Legacy pod-based deployment (backward compatible)
              image:
                type: string
                description: "Container image for pod-based deployment (legacy)"
              binary:
                type: string
                description: "Binary command for pod-based deployment (legacy)"
              
              # Helm-based deployment configuration
              helmChart:
                type: object
                description: "Helm chart configuration for component deployment"
                properties:
                  repository:
                    type: string
                    description: "Helm chart repository URL"
                  name:
                    type: string
                    description: "Helm chart name"
                  version:
                    type: string
                    description: "Helm chart version"
                  releaseName:
                    type: string
                    description: "Custom Helm release name (optional, defaults to CR name)"
                  crdsStrategy:
                    type: string
                    description: "How to handle CRDs contained in the chart: Auto (default) skips if CRDs already exist, Install always installs CRDs, Skip never installs CRDs"
                    enum: ["Auto", "Install", "Skip"]
                    default: "Auto"
              
              # Helm values configuration
              values:
                type: object
                x-kubernetes-preserve-unknown-fields: true
                description: "Inline Helm values (YAML object)"
              
              valuesFiles:
                type: array
                description: "References to ConfigMaps or Secrets containing values files"
                items:
                  type: object
                  properties:
                    kind:
                      type: string
                      enum: ["ConfigMap", "Secret"]
                      description: "Type of resource containing values"
                    name:
                      type: string
                      description: "Name of ConfigMap or Secret"
                    key:
                      type: string
                      description: "Key within the ConfigMap or Secret containing values YAML"
                  required:
                    - kind
                    - name
                    - key
              
              # Deployment target namespace
              targetNamespace:
                type: string
                description: "Target namespace for Helm installation (optional, defaults to CR namespace)"
              
              # AppStack configuration for multi-component deployments with dependencies
              appStack:
                type: object
                description: "Multi-component application stack with dependency management"
                properties:
                  components:
                    type: array
                    description: "List of components to deploy in order with dependencies"
                    items:
                      type: object
                      required:
                        - name
                      properties:
                        name:
                          type: string
                          description: "Component name (unique identifier)"
                        description:
                          type: string
                          description: "Component description"
                        enabled:
                          type: boolean
                          description: "Enable or disable this component (default: true)"
                          default: true
                        dependsOn:
                          type: array
                          description: "List of component names this component depends on"
                          items:
                            type: string
                        helmChart:
                          type: object
                          description: "Helm chart configuration for this component"
                          properties:
                            repository:
                              type: string
                              description: "Helm chart repository URL"
                            name:
                              type: string
                              description: "Helm chart name"
                            version:
                              type: string
                              description: "Helm chart version"
                            releaseName:
                              type: string
                              description: "Custom Helm release name (optional, defaults to component name)"
                            crdsStrategy:
                              type: string
                              description: "How to handle CRDs contained in the chart: Auto (default) skips if CRDs already exist, Install always installs CRDs, Skip never installs CRDs"
                              enum: ["Auto", "Install", "Skip"]
                              default: "Auto"
                        kubernetesManifest:
                          type: string
                          description: "Raw Kubernetes YAML manifest (alternative to Helm chart)"
                        values:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                          description: "Inline Helm values for this component"
                        valuesFiles:
                          type: array
                          description: "References to ConfigMaps or Secrets containing values files"
                          items:
                            type: object
                            properties:
                              kind:
                                type: string
                                enum: ["ConfigMap", "Secret"]
                                description: "Type of resource containing values"
                              name:
                                type: string
                                description: "Name of ConfigMap or Secret"
                              key:
                                type: string
                                description: "Key within the ConfigMap or Secret containing values YAML"
                            required:
                              - kind
                              - name
                              - key
                        targetNamespace:
                          type: string
                          description: "Target namespace for this component (optional)"
                        waitForReady:
                          type: boolean
                          description: "Wait for component to be ready before proceeding (default: true)"
                          default: true
                        readinessCheck:
                          type: object
                          description: "Custom readiness check configuration"
                          properties:
                            type:
                              type: string
                              enum: ["pod", "deployment", "statefulset", "job", "custom"]
                              description: "Type of readiness check"
                            name:
                              type: string
                              description: "Optional resource name to wait on (e.g., a specific deployment name). If set, selector/matchLabels are ignored."
                            selector:
                              type: string
                              description: "Label selector for readiness (kubectl-style). For multiple conditions, separate with commas (e.g., 'app.kubernetes.io/instance=prometheus-adapter,app.kubernetes.io/name=prometheus-adapter'). Use matchLabels for map-style."
                            matchLabels:
                              type: object
                              description: "Kubernetes-style matchLabels map (alternative to selector)"
                              additionalProperties:
                                type: string
                            namespace:
                              type: string
                              description: "Optional namespace override for the readiness check (defaults to component/CR namespace)"
                            timeout:
                              type: integer
                              description: "Timeout in seconds (default: 300)"
                              default: 300
          
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
              releaseStatus:
                type: string
                description: "Status of the Helm release (single component deployments)"
              releaseName:
                type: string
                description: "Name of the Helm release (single component deployments)"
              releaseVersion:
                type: integer
                description: "Version/revision of the Helm release (single component deployments)"
              
              # AppStack-specific status
              componentStatus:
                type: array
                description: "Status of individual components in AppStack"
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "Component name"
                    phase:
                      type: string
                      description: "Current phase: Pending, Installing, Ready, Failed"
                      enum: ["Pending", "Installing", "Ready", "Failed", "Disabled"]
                    releaseName:
                      type: string
                      description: "Helm release name for this component"
                    releaseVersion:
                      type: integer
                      description: "Helm release version/revision"
                    message:
                      type: string
                      description: "Status message"
                    lastTransitionTime:
                      type: string
                      format: date-time
                      description: "Last time the status changed"
              appStackPhase:
                type: string
                description: "Overall AppStack deployment phase"
                enum: ["Pending", "Installing", "Ready", "Failed", "Degraded"]

  names:
    kind: WekaAppStore
    plural: wekaappstores
  scope: Namespaced
{{- end }}