apiVersion: v1
kind: Secret
metadata:
  name: csi-wekafs-api-secret
  namespace: csi-wekafs
type: Opaque
data:
  username: Y3NpLTE=
  password: UEFzc3dvcmQxMjM=
  organization: Um9vdA==
  endpoints: MTcyLjMuMS4xMTQ6MTQwMDAsMTcyLjMuMy4yNDA6MTQwMDAsMTcyLjMuOC4zOToxNDAwMCwxNzIuMy4wLjE1NToxNDAwMCwxNzIuMy4xMy45ODoxNDAwMCwxNzIuMy40LjI0ODoxNDAwMA==
  scheme: aHR0cAo=


